// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AddEdge(arg1:string):Promise<void>;

export function CountDueNodes(arg1:number):Promise<number>;

export function Create(arg1:string,arg2:string,arg3:number):Promise<number>;

export function Delete(arg1:number):Promise<void>;

export function DeleteEdge(arg1:string):Promise<void>;

export function GetCurrentFEN():Promise<string>;

export function GetCurrentID():Promise<number>;

export function GetCurrentRepCoverage():Promise<number>;

export function GetCurrentWinrates():Promise<backend.PositionWinrate>;

export function GetDueFENs():Promise<Array<string>>;

export function GetSelectedID():Promise<number>;

export function List():Promise<Array<backend.Repertoire>>;

export function ListEdges():Promise<Array<string>>;

export function PlayMoveSAN(arg1:string):Promise<void>;

export function SelectRepertoire(arg1:number):Promise<void>;

export function SetCurrentFEN(arg1:string):Promise<void>;

export function SetCurrentID(arg1:number):Promise<void>;

export function TestCurrentPosition(arg1:string):Promise<void>;

export function TestCurrentPositionWithDueDate(arg1:string):Promise<void>;

export function Update(arg1:backend.Repertoire):Promise<void>;
