// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEdge(arg1) {
  return window['go']['backend']['RepertoireManager']['AddEdge'](arg1);
}

export function CountDueNodes(arg1) {
  return window['go']['backend']['RepertoireManager']['CountDueNodes'](arg1);
}

export function Create(arg1, arg2, arg3) {
  return window['go']['backend']['RepertoireManager']['Create'](arg1, arg2, arg3);
}

export function Delete(arg1) {
  return window['go']['backend']['RepertoireManager']['Delete'](arg1);
}

export function DeleteEdge(arg1) {
  return window['go']['backend']['RepertoireManager']['DeleteEdge'](arg1);
}

export function GetCurrentFEN() {
  return window['go']['backend']['RepertoireManager']['GetCurrentFEN']();
}

export function GetCurrentID() {
  return window['go']['backend']['RepertoireManager']['GetCurrentID']();
}

export function GetCurrentRepCoverage() {
  return window['go']['backend']['RepertoireManager']['GetCurrentRepCoverage']();
}

export function GetCurrentWinrates() {
  return window['go']['backend']['RepertoireManager']['GetCurrentWinrates']();
}

export function GetDueFENs() {
  return window['go']['backend']['RepertoireManager']['GetDueFENs']();
}

export function GetSelectedID() {
  return window['go']['backend']['RepertoireManager']['GetSelectedID']();
}

export function List() {
  return window['go']['backend']['RepertoireManager']['List']();
}

export function ListEdges() {
  return window['go']['backend']['RepertoireManager']['ListEdges']();
}

export function PlayMoveSAN(arg1) {
  return window['go']['backend']['RepertoireManager']['PlayMoveSAN'](arg1);
}

export function SelectRepertoire(arg1) {
  return window['go']['backend']['RepertoireManager']['SelectRepertoire'](arg1);
}

export function SetCurrentFEN(arg1) {
  return window['go']['backend']['RepertoireManager']['SetCurrentFEN'](arg1);
}

export function SetCurrentID(arg1) {
  return window['go']['backend']['RepertoireManager']['SetCurrentID'](arg1);
}

export function TestCurrentPosition(arg1) {
  return window['go']['backend']['RepertoireManager']['TestCurrentPosition'](arg1);
}

export function TestCurrentPositionWithDueDate(arg1) {
  return window['go']['backend']['RepertoireManager']['TestCurrentPositionWithDueDate'](arg1);
}

export function Update(arg1) {
  return window['go']['backend']['RepertoireManager']['Update'](arg1);
}
